[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"

# [env]
# WiFi configuration fallback defaults
# These are now handled by build.rs which loads from .env file
# Recommended: Use .env file or environment variables instead
# WIFI_SSID = ""
# WIFI_PASSWORD = ""

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]
